### ISSUE TITLE
Incorrect dependency in class TurnTo\SocialCommerce\Block\TurnToConfig

### ISSUE THREAD

**Issue by siarzukpiatrouski** [turnto/magento2-turnto-socialcommerce#102]
Hey,

incorrect dependency in class TurnTo\SocialCommerce\Block\TurnToConfig - \Magento\Store\Model\StoreManagerInterface already exists in context object. You can get storeManager from context.

**Comment by rholgate-turnto** [comment]
Hi,

this issue has been resolved by the following commit:
https://github.com/turnto/magento2-turnto-socialcommerce/commit/b88759457956e64dd71d8735704a65d494374792

Please let us know if you have any further questions or concerns
