### ISSUE TITLE
Invalid template file: 'TurnTo_SocialCommerce::system/config/exportCatalog.phtml'

### ISSUE THREAD

**Issue by vk-chts** [turnto/magento2-turnto-socialcommerce#118]
The attached exportcatalog.phtml file is having wrong name defined in the block thus throwing error in admin
File is called using **exportCatalog.phtml**
and the file present in the directory is **exportcatalog.phtml**

Please either change the file name or change in from the file 
-> Block/System/Config/ExportCatalog.php
![Screenshot from 2020-08-10 18-32-34](https://user-images.githubusercontent.com/41280230/89785371-f21ea400-db37-11ea-98ed-263df5471576.png)

**Comment by vk-chts** [comment]
@erikhansen @LordZardeck @ntoombs19 @ericthehacker 
Can anyone please provide this issue update. I need to upgrade the module but not with this issue.

**Comment by rholgate-turnto** [comment]
This fix was made almost 2 months ago and is available in any version since that update. Please update your module version.
