### ISSUE TITLE
Product feed export performance issue

### ISSUE THREAD

**Issue by dambrogia** [turnto/magento2-turnto-socialcommerce#170]
The URL rewrite table is queried once for every product that is being exported [reference](https://github.com/turnto/magento2-turnto-socialcommerce/blob/4cd9421cd11f5edc4a163139740975c09fb62a0d/Model/Export/AbstractExport.php#L194-L211). We have a catalog of 60k+ products (which in reality is not that large). As of 3.2 batching products occurs for retrieving products, but still for each product another url-rewrite occurs. This is a large performance issue.

### Preconditions

No preconditions are required to reproduce this issue. However for solidarity:
1. PHP 7.2
2. MariaDB 10.3
3. Currently on module version 3.2 but this exists in the active/development branch as well.

### Steps to reproduce

1. Have any number of products in your store
2. Enable the product feed export
3. Run the product feed export

### Expected result

1. Database queries should not be run in a loop

### Actual result

1. Database query is currently being run in a for loop

____

This can efficiently be grabby by joining the rewrite table when gathering products or gathering all the ids of the products and querying them once per batch of products, then looking them up by their product id.

#### This is the method being called in a loop:
![image](https://user-images.githubusercontent.com/6516452/103313954-6ae2a780-49d6-11eb-83c0-c96c767b0f02.png)

#### This is the loop it is being called in (notice stack trace):
![image](https://user-images.githubusercontent.com/6516452/103314039-af6e4300-49d6-11eb-901f-5cef10c4c942.png)

**Comment by ptrollinspt** [comment]
This has been refactored in v3.8.3 to be more efficient and cache urls.
