### ISSUE TITLE
Getting Console Error When Disable Tunto for Specifc Website

### ISSUE THREAD

**Issue by TheRealHunzik** [turnto/magento2-turnto-socialcommerce#220]
### Preconditions

1. Magento 2.3.4-p2 with Multi Website Setup
2. Tunto Social Commerce - 3.8.1

### Steps to reproduce
1. Disable TUnto for a Specific Site from configurations
2. Go to Any Product Detail Page for TUrnto Disabled Website
3. Open Developer Console Error Section

### Expected result
1. No Errors Should Appear

### Actual result
1. JS Error appearing `Uncaught TypeError: window.TurnToCmd is not a function`
![image](https://user-images.githubusercontent.com/51072292/175248708-e8ef0f67-c385-44b6-9765-f8986cb0fea4.png)
2. the issue is in vendor/turnto/social-commerce/view/frontend/templates/product/view/config.phtml:39

**Comment by brianshenPixleeTurnto** [comment]
Hi TheRealHunzik,

We are looking into your issue. We will keep you posted.

Thank you,

Brian

**Comment by TheRealHunzik** [comment]
@brianshenPixleeTurnto is there any update?

**Comment by brianshenPixleeTurnto** [comment]
Hi @TheRealHunzik. I recall we resolved this on a call. I will close.
