### ISSUE TITLE
Upload product feed cron issue - cronUploadFeed method

### ISSUE THREAD

**Issue by SecRetF** [turnto/magento2-turnto-socialcommerce#227]
In version 3.8.3, the loop condition in the 'do-while' construct is imprecise in the `TurnTo\SocialCommerce\Model\Export\Catalog::cronUploadFeed` method. The `$feed` consistently returns false on the last iteration, yet the loop body is still executed once. Also, `$page++` is called repeatedly.

![image](https://github.com/turnto/magento2-turnto-socialcommerce/assets/96160506/ebf2de59-72e1-4c35-9846-1b2d202f39e7)

### Preconditions
1. turnto/social-commerce 3.8.3
2. Magento 2.4.6

### Steps to reproduce
1. Enable configuration: Product Feed -> Enable Automated Feed Submission 
3. Click "Export Catalog" of "Export Product Catalog to the TurnTo system" Or run socialcommerce_exportcatalog cron job

### Expected result
No exceptions should be thrown

### Actual result
Throw an exception "Call to a member function asXML() on bool at */vendor/turnto/social-commerce/Service/GoogleFeed/Client.php:57"

### My Patch as a reference
Remove the first `$page++`, update the loop condition to `$feed && $page <= $this->totalPages`
```
do {
    $feed = $this->generateProductFeed($store, $page);
    try {
        $fileName = sprintf('%s_of_%s_store_%s_%s', $page, $this->totalPages, $store->getId(), self::FEED_STYLE);
        $this->feedClient->transmitFeedFile($feed, $fileName, self::FEED_STYLE, $store->getCode());
    } catch (Exception $e) {
        $this->logger->error(
            "TurnTo catalog export error sending page $page.",
            [
                'exception' => $e
            ]
        );
    }
    $page++;
} while ($feed && $page <= $this->totalPages);
```

**Comment by ptrollinspt** [comment]
@SecRetF thank you for the feedback.

[Release 3.8.4](https://github.com/turnto/magento2-turnto-socialcommerce/releases/tag/v3.8.4) is now available. This release fixes the loop logic. It also has some additional bug fixes and optimizations.
