### ISSUE TITLE
Loading products in a loop on a PLP causing serious performance issues

### ISSUE THREAD

**Issue by erikhansen** [turnto/magento2-turnto-socialcommerce#228]
### Preconditions
1. We're using version 3.8.2 of this extension on Adobe Commerce 2.4.5-p5

### Steps to reproduce
1. Install extension and configure it like this:
![298776155-aefc75b7-3f2f-480f-ae2d-61855304bbce](https://github.com/turnto/magento2-turnto-socialcommerce/assets/129031/df02d156-6974-4a3a-b69a-01e488046262)

### Expected result
1. Product listing pages should load in nearly the same amount of time compared to before extension was enabled

### Actual result
1. PLP loads far more slowly, due to products being loaded in a loop in `\TurnTo\SocialCommerce\Plugin\Review\Block\Product\ReviewRenderer::aroundGetReviewsCount` https://github.com/turnto/magento2-turnto-socialcommerce/blob/v3.8.3/Plugin/Review/Block/Product/ReviewRenderer.php#L80

I uncovered this while doing a Blackfire profile of a client's production site: 

![Untitled profile - Blackfire 2024-01-22 19-24-12](https://github.com/turnto/magento2-turnto-socialcommerce/assets/129031/3e3a2553-05fd-4142-9dce-627cf9dab090)

![Untitled profile - Blackfire 2024-01-22 19-25-27](https://github.com/turnto/magento2-turnto-socialcommerce/assets/129031/e5dedd5c-8643-46e9-8e66-42207853f0cc)

**Comment by erikhansen** [comment]
@ptrollinspt Hello! How soon do you think you'd be able to refactor this code to load the necessary data in a collection/repository once, rather than loading each product individually? This issue is seriously impacting a client's site that is really high traffic.

**Comment by erikhansen** [comment]
@ptrollinspt It looks like the change to using a product repository to load a product in a loop was made back in Oct of 2021: 

https://github.com/turnto/magento2-turnto-socialcommerce/commit/d96bac517eb099997e908d698ddda506aca25677#diff-449ad4de046340fd7b50f1a5d99fc2482b08852aae993d380ea30a626a2f0d22R121

My guess is that the developer was not aware that the code change would cause the product model to be reloaded for every product on a category.

In order for a product attribute to be accessible from the product model on a PLP _without_ reloading it, the `Used in Product Listing` value needs to be set to `Yes`. The `turnto_review_count` attribute is currently set to "No". I'm thinking you'll need to write a setup script to change the `Used in Product Listing` value to "Yes" (or in some other way, get the necessary product attributes to be loaded in the PLP collection).

**Comment by ptrollinspt** [comment]
@erikhansen thank you for the feedback. 

[Release 3.8.4](https://github.com/turnto/magento2-turnto-socialcommerce/releases/tag/v3.8.4) is now available. This release adds a patch to use the attributes in product listing and removes the product load. It also has some additional bug fixes.

**Comment by erikhansen** [comment]
@ptrollinspt That was fast, thanks!
