### ISSUE TITLE
Product flat indexer

### ISSUE THREAD

**Issue by daniel-ifrim** [turnto/magento2-turnto-socialcommerce#23]
Issue: If a merchant has [enabled flat indexes](https://user-images.githubusercontent.com/129031/32190890-40430044-bd7d-11e7-9df0-93f741a64d7a.png), when the nightly CRON job runs, the flat indexes are not reindexed.

In `TurnTo\SocialCommerce\Model\Import\Ratings`

```
} finally {
    if (!empty($productIdsToReindex) && !$this->productEavIndexProcessor->getIndexer()->isScheduled()) {
        $this->productEavIndexProcessor->reindexList(array_unique($productIdsToReindex));
    }
}
```

It needs to reindex flat product index too if it's enabled.
Also, for both indexers you'd need to add a condition to test if indexer is valid (isValid).
See `indexer_state` table and `Magento\Catalog\Model\Indexer\AbstractFlatState` `Magento\Catalog\Model\Indexer\Product\Flat\State`.

Thank you

**Comment by erikhansen** [comment]
This issue was fixed in [release 1.3.0](https://github.com/turnto/magento2-turnto-socialcommerce/releases). Please install the latest version of this extension and let me know whether your issue has been resolved.
