### ISSUE TITLE
Unecessary version bump causing downtime during release

### ISSUE THREAD

**Issue by dambrogia** [turnto/magento2-turnto-socialcommerce#230]
### Preconditions

1. Current version 3.8.2

### Steps to reproduce

1. composer require turnto/social-commerce 3.8.3

### Expected result

1. No Schema Update required since data/schema does not change

### Actual result

```
magerun sys:setup:compare-versions

+-------------------------------------+----------------+----------------+----------------+--------+
| Setup                               | Module         | DB             | Data           | Status |
+-------------------------------------+----------------+----------------+----------------+--------+
| xxx                                 | 2.0.2          | 2.0.2          | 2.0.2          | OK     |
...
| xxx                                 | 2.0.0          | 2.0.0          | 2.0.0          | OK     |
| TurnTo_SocialCommerce               | 3.8.3          | 3.8.1          | 3.8.1          | Error  |
+-------------------------------------+----------------+----------------+----------------+--------+


  1 setup error was found!
```

Although if we compare the releases, there is no schema that is actually changed. See the reference below:
- https://github.com/turnto/magento2-turnto-socialcommerce/compare/v3.8.2...v3.8.3

I realize this is a past release so there is nothing that can be done now. However, this issue will cause us downtime on our release that is not necessary unless we patch the following value back to `3.8.1` before release -- which we will do.

- https://github.com/turnto/magento2-turnto-socialcommerce/commit/909079d3af3c62ab9609b68ffd2e6763b7ba1a7b#diff-cfc6d0cac6c218df3440a678610688f93f9628a67a457c49030a50f4e7fc50d5R9

**Comment by ptrollinspt** [comment]
@dambrogia I'll note this for future releases. Also, https://github.com/turnto/magento2-turnto-socialcommerce/releases/tag/v3.8.4 is available with some bug fixes and improvements.
