### ISSUE TITLE
Product feed improvement 

### ISSUE THREAD

**Issue by molsm** [turnto/magento2-turnto-socialcommerce#25]
I think it will be good to have such features:

1. Product feed export and upload to TurnTo system through CLI.
2. Configurable cron expression in admin BE. Right now it is hardcoded in xml file!?

@erikhansen 
What do you think? 
Are you interested in contributing of such things? Currently we are thinking to extend this module.

**Comment by erikhansen** [comment]
@molsm If you submitted a pull request that added both or either of those features, I would merge it into this repo. Please make sure you follow the [Magento coding standards](http://devdocs.magento.com/guides/v2.0/coding-standards/bk-coding-standards.html).

**Comment by erikhansen** [comment]
@molsm If you're interested in seeing the contents of the product feed that is sent to TurnTo, here is quick way to see that: https://github.com/turnto/magento2-turnto-socialcommerce/issues/27#issuecomment-357345453

**Comment by erikhansen** [comment]
@molsm I'm going to close this issue, but as I mentioned earlier, I'd be happy to accept a PR implementing either of these features.
