### ISSUE TITLE
TurnTo\SocialCommerce\Controller\Ajax\Media class is not compatible with Magento 2.2.2

### ISSUE THREAD

**Issue by molsm** [turnto/magento2-turnto-socialcommerce#26]
### Preconditions
1. Magento 2.2.2
2. Deploy mode -> any

### Steps to reproduce
1. Execute `php bin/magento setup:di:compile`

### Expected result
1. Compiling is finished without an any errors.

### Actual result

```
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 1 min 458.0 MiBErrors during compilation:
	TurnTo\SocialCommerce\Controller\Ajax\Media
		Incompatible argument type: Required type: \Magento\Catalog\Model\ProductFactory. Actual type: \Magento\Swatches\Helper\Data; File:
/private/var/www/project/magento/app/code/TurnTo/SocialCommerce/Controller/Ajax/Media.php

Total Errors Count: 1


  [Magento\Framework\Validator\Exception]
  Error during compilation


setup:di:compile
```

### Details

Magento (version 2.2.2) has changed class injection order in Media class constructor

**Comment by erikhansen** [comment]
I've fixed this issue in the `feature/2-2-support` branch (see [this PR for details](https://github.com/turnto/magento2-turnto-socialcommerce/pull/28)). Can you install this version of the extension and confirm that this fixes your issue?

How to install it via Composer:

```
composer require turnto/social-commerce:dev-feature/2-2-support
```

**Comment by molsm** [comment]
@erikhansen Ok. Thanks will test. 

Can you please do new release (tag repo) so we can get it from composer?

Best regards,

**Comment by erikhansen** [comment]
@molsm Refer to my [instructions above](https://github.com/turnto/magento2-turnto-socialcommerce/issues/26#issuecomment-357818976) for details on how to install this specific branch via Composer. Once you test this branch, I will then tag a new release.

**Comment by molsm** [comment]
Hello @erikhansen ,

Your fix is working. Thank you.
