### ISSUE TITLE
Magento 2.2.x doesn't support the "Use child SKU instead of parent SKU" option

### ISSUE THREAD

**Issue by erikhansen** [turnto/magento2-turnto-socialcommerce#29]
The variant SKU functionality does not work on Magento 2.2.x.

### Preconditions

1. Install Magento 2.2.2 with sample data
2. Install the TurnTo extension, enable it, and change the "Use child SKU instead of parent SKU" option to "Yes".

### Steps to reproduce

1. Go to a configurable product page (e.g., beaumont-summit-kit.html)
2. Select a size or color swatch

### Expected result

1. The `TurnTo.reset({"sku": response.sku});` and `TurnToChatter.reset({"sku": response.sku});` code ([see here](https://github.com/turnto/magento2-turnto-socialcommerce/blob/1.2.0/view/frontend/web/js/swatch-renderer-mixin.js#L32..L40)) should be called to tell TurnTo that a different SKU has been selected

### Actual result
1. The TurnTo JS will not be called. The reason for this is that in 2.2.x, the swatch JS was optimized so that an AJAX call doesn't have to be made to the server every time a swatch is selected. Here is a comparison of a 2.1.x vs 2.2.x swatch selection:
![10-12-34 beaumont summit kit - jackets - tops - men-cmggo](https://user-images.githubusercontent.com/129031/34998905-e9e5b456-faa5-11e7-9ee6-aa8b4eca3fd1.png)
Since the [TurnTo code](https://github.com/turnto/magento2-turnto-socialcommerce/blob/1.2.0/view/frontend/web/js/swatch-renderer-mixin.js#L32..L40) was based on the expectation that there would be an AJAX call, the code never gets run in 2.2.x. 

A potential fix for this: The TurnTo extension could add the `sku` data to the `this.options.jsonConfig.images` object referenced in [the core code](https://github.com/magento/magento2/blob/2.2.2/app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js#L290). The TurnTo extension would then need to hook into the appropriate method in the [`swatch-renderer.js`](https://github.com/magento/magento2/blob/2.2.2/app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js) file that gets called whenever the swatches are selected, and that code would need to call the `TurnTo.reset({"sku": <SKU VARIABLE>});` and `TurnToChatter.reset({"sku": <SKU VARIABLE>});` methods.

**Comment by LordZardeck** [comment]
Closing this issue as this was fixed in the latest [2.0.0 release](https://github.com/turnto/magento2-turnto-socialcommerce/releases/latest)
