### ISSUE TITLE
Magento Swatches Media constructor changed in 2.3.1 and missing method in config helper

### ISSUE THREAD

**Issue by davidtayba** [turnto/magento2-turnto-socialcommerce#57]
### Preconditions
1. Magento 2.3.1
2. PHP 7.2, MySQL 5.7

### Steps to reproduce
1. Click on swatch thumbnail on product listing page/category products 
2. An ajax call is made to TurnTo\SocialCommerce\Controller\Ajax\Media which overrides Magento\Swatches\Controller\Ajax\Media.
3. In 2.3.1 the constructor has changed for Magento\Swatches\Controller\Ajax\Media 
4. Also the helper TurnTo\SocialCommerce\Helper\Config needs to have a getUseChildSku method.
5. Server throws a 500 error.

### Expected result
1. Swatch returns JSON without issue.

### Actual result
1. Server throws a 500 issue.

**Comment by joshfedo** [comment]
Thanks for reporting this bug! What release version of the module are you currently on?

**Comment by davidtayba** [comment]
We're using this in our composer.json:
`        "turnto/social-commerce": "^3.0.2",
`

**Comment by sergey-fedosimov** [comment]
The same for 2.2.10

**Comment by rholgate-turnto** [comment]
I believe this was fixed some time ago. If I'm mistaken, please re-open the issue.
