### ISSUE TITLE
Historical Orders Feed Cron fails on some environments

### ISSUE THREAD

**Issue by martin-cod** [turnto/magento2-turnto-socialcommerce#59]
### Preconditions
Magento is running on Webscale Magento PRO plan. 
Issue is not related to server file permissions policy, because target directory is writable for current user.

### Expected result
Cron is completed successfully

### Actual result
`[2019-09-19 18:00:22] turnto.ERROR: An error occurred while processing Historical Orders Feed Cron
{"storeId":"2","exception":"[object] (Exception(code: 0): Warning: fopen(var/tmp/tuntoexport.csv): failed to open
stream: No such file or directory in /var/www/staging/vendor/turnto/socialcommerce/Model/Export/Orders.php on line 183 at
/var/www/staging/vendor/magento/framework/App/ErrorHandler.php:61)"} []`

**Comment by martin-cod** [comment]
I can assume that this issue is related to server environment configuration because it is reproducible only on rare servers. 
The following construction `fopen(var/tmp/tuntoexport.csv);` tries to create a file in the directory different from Magento's `var/tmp` because relative path is sued.

**Comment by martin-cod** [comment]
@joshfedo  please review the PR #60

**Comment by joshfedo** [comment]
@martin-cod This improvement is live in versions  >= v3.0.4
