### ISSUE TITLE
Incompatibility with Magento 2.3.3

### ISSUE THREAD

**Issue by johnekj** [turnto/magento2-turnto-socialcommerce#68]
There is issue constructor method in https://github.com/turnto/magento2-turnto-socialcommerce/blob/1815eee9df1256c15139f04fbd8506b3f1a3c014/Controller/SSO/CreatePost.php#L81-L100

In Magento 2.3.3 the parent __construct method has one more required argument:
https://github.com/magento/magento2/blob/d5104d52fc5e07f88be373ae2bc6a61d4d98c939/app/code/Magento/Customer/Controller/Account/CreatePost.php#L195

When I install your extension, DI compilation in Magento fails with error:

> TurnTo\SocialCommerce\Controller\SSO\CreatePost Missed required argument customerRepository in parent::__construct call.

**Comment by joshfedo** [comment]
Thanks you for reporting this issues. We will look into this and create a patch.

**Comment by sankalpshekhar** [comment]
@johnekj  This has been fixed in v3.0.5

**Comment by joshfedo** [comment]
This bug has been fixed in 3.0.5.
