### ISSUE TITLE
ReviewRenderer Template Names Not Consistent - Preventing Render

### ISSUE THREAD

**Issue by loganstellway** [turnto/magento2-turnto-socialcommerce#91]
### Preconditions

1. Magento Version: `2.3.3-p1`
2. PHP Version: `7.2.24`
3. Plugin preference for `Magento\Catalog\Block\Product\ReviewRendererInterface`, adding an additional template to the `$_availableTemplates` variable. 

### Steps to reproduce

1. Navigate to a product list page (category, search)

### Expected result

1. Product review summaries will show

### Actual result

1. Reviews do not show
2. Error log:
>Invalid template file: 'helper/summary_short.phtml' in module: 'Vendor_Module'

### Solution
This can be resolved by adding the `Magento_Review::` namespace prefix to the template paths, like in the core module. 
- [Reference to Magento_Review:: _availableTemplates](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Review/Block/Product/ReviewRenderer.php#L27-L30)
- [Reference to TurnTo_ SocialCommerce::_availableTemplates](https://github.com/turnto/magento2-turnto-socialcommerce/blob/master/Plugin/Review/Block/Product/ReviewRenderer.php#L41-L44)

**Comment by rholgate-turnto** [comment]
Hi @loganstellway thanks for the submission.

I was unable to recreate your issue after a number of attempts. I do notice that your included error is for "module: 'Vendor_Module'". Does this indicate that the error was in another module, or did you use this as a placeholder name when posting the error?

Ultimately I agree that the change made sense, and my testing showed it caused no new errors, so the change was made and went out in the most recent release, 3.2.2.

**Comment by loganstellway** [comment]
Sorry for the late reply
_(I have a bit of a cluttered inbox 😅)_

But thank you very much for the update!
